version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: ${DOCKERFILE-dockerfile}
    depends_on:
      - db
    environment:
      DSN: ${DSN-postgresql://postgres:the_beast_password@db:5432/gorm}
      API_VERSION: "1.0.0"
    ports:
      - "8000:8000"
    volumes:
      - ./:/go-server
      - /go-server/static
    restart: always
  db:
    environment:
      POSTGRES_PASSWORD: the_beast_password
      POSTGRES_DB: gorm
      PGDATA: /var/lib/postgresql/data/pgdata
    image: postgres:16.2-alpine3.19
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432
    restart: always
volumes:
  db_data:
