version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: ${DOCKEFILE-dockerfile}
    depends_on:
      - db
    environment:
      DSN: ${DSN-golang:golang@tcp(db:3306)/gorm?charset=utf8mb4&parseTime=True&loc=Local}
      API_VERSION: "1.0.0"
    ports:
      - "8000:8000"
    volumes:
      - ./:/go-server
      - /go-server/static
    restart: unless-stopped
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=golang
      - MYSQL_PASSWORD=golang
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db_data:
