FROM golang:1.21.1-alpine AS builder
WORKDIR /go-server
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build .

# Path: /app
FROM scratch
WORKDIR /app
COPY --from=builder /go-server/go-server .
CMD ["/app/go-server"]