# fly.toml app configuration file generated for chaoticteam on 2024-03-03T03:04:43-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chaoticteam'
primary_region = 'mia'

[build]
  dockerfile = 'dockerfile.prod'

[http_service]
  internal_port = 8000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_unavailable = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
